setwd("/Users/davidzhu/Desktop/Datathon Materials/datathon/data")
#req311 = read.csv("311_service_requests.csv")
#foodInsp = read.csv("food_establishment_inspections.csv")
#commHealth = read.csv("community_health.csv")
#demCity = read.csv("demographics_city.csv")
#demState = read.csv("demographics.csv")
#envRad = read.csv("environmental_radiation.csv")
#foodVenues = read.csv("food_venues.csv")
#geo = read.csv("geographic.csv")
