#install.packages("R.utils")
library(R.utils)
setwd("/Users/davidzhu/Desktop/Datathon Materials/datathon/data")
#req311 = read.csv("311_service_requests.csv.gz")
#foodInsp = read.csv("food_establishment_inspections.csv.gz")
#commHealth = read.csv("community_health.csv")
#demCity = read.csv("demographics_city.csv")
#demState = read.csv("demographics.csv")
#envRad = read.csv("environmental_radiation.csv")
#foodVenues = read.csv("food_venues.csv.gz")
#geo = read.csv("geographic.csv")

#write.csv(foodVenues, "food_venues_R.csv")
#gzip("food_venues_R.csv")
#foodInsp2 = subset(foodInsp, select = -c(X, X.1))
#write.csv(foodInsp2, "food_establishment_inspections_R.csv")
#gzip("food_establishment_inspections_R.csv")
